server:
  port: 8081
#spring.cloud.nacos.config.server-addr=127.0.0.1:8848 //在 bootstrap.properties|bootstrap.yml 中配置 Nacos server 的地址和应用名
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848 //在 application.properties|application.yml 中配置 Nacos server 的地址
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.66:8848 #注意这个的discovery和bootstrap.yml的config!!!两个都要同时配置
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"